
# SMTP 설정

spring:
  mail:
    host: smtp.gmail.com # SMTP 서버 (Gmail 예시)
    port: 587            # SMTP 포트
    username: o3ozvoo@gmail.com # 발신 이메일 주소
    password: axhuatjvcwltwwgp  # 발신 이메일 비밀번호 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true         # 인증 활성화
          starttls:
            enable: true     # TLS 암호화 활성화

  # 네이버 간편로그인

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: WHM3kCHtaWn1Qz1VYbI8
            client-secret: Sdxf9olu0T
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    datetime-format: yyyy-MM-dd

  web:
    resources:
      static-locations: classpath:/

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none    #create 금지
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  logging:
#    level:
#      org.springframework.security: DEBUG

uploadDir: /Users/nana/Documents/work/uploads
